name: AClib
version: 1.3
date: 2018-03-11
description: |
    Almost Crystallographic Groups - A Library and Algorithms

authors:
    - name: Karel Dekimpe
      url: https://www.kuleuven-kulak.be/~dekimpe/
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

maintainers:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

GAP: ">=4.7"

needed-pkgs:
    - name: "polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"

suggested-pkgs:
    - name: "crystcat"
      version: ">=1.1"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap45/packages.php"

www: https://gap-packages.github.io/aclib/
readme: README
packageinfo: https://gap-packages.github.io/aclib/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/aclib/releases/download/v1.3/aclib-1.3.tar.gz

abstract: |
    The <span class="pkgname">AClib</span> package contains a library of almost crystallographic groups and a some algorithms to compute with these groups. A group is called almost crystallographic if it is finitely generated nilpotent-by-finite and has no non-trivial finite normal subgroups. Further, an almost crystallographic group is called almost Bieberbach if it is torsion-free. The almost crystallographic groups of Hirsch length 3 and a part of the almost cyrstallographic groups of Hirsch length 4 have been classified by Dekimpe. This classification includes all almost Bieberbach groups of Hirsch lengths 3 or 4. The AClib package gives access to this classification; that is, the package contains this library of groups in a computationally useful form. The groups in this library are available in two different representations. First, each of the groups of Hirsch length 3 or 4 has a rational matrix representation of dimension 4 or 5, respectively, and such representations are available in this package. Secondly, all the groups in this libraray are (infinite) polycyclic groups and the package also incorporates polycyclic presentations for them. The polycyclic presentations can be used to compute with the given groups using the methods of the Polycyclic package.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
